spring.application.name=aivice
spring.mongodb.uri=mongodb+srv://abhishek17007a_db_user:e9MR52GPXQUHPlBb@cluster0.1swnhwn.mongodb.net/aivice?retryWrites=true&w=majority
spring.mongodb.database=aivice_db
logging.level.org.springframework.data.mongodb=DEBUG

# JWT
jwt.secret=f01654c714a9152ec116c33a860210298e6153234b55c6070ddcb5f54c429c465f68d111200fc35bf04865d9dd9609f1442ec4c64cfd6bd0d20f6a3279a3216d
jwt.expiration=86400000