spring.application.name=aivice
spring.mongodb.uri=mongodb+srv://abhishek17007a_db_user:e9MR52GPXQUHPlBb@cluster0.1swnhwn.mongodb.net/aivice?retryWrites=true&w=majority
spring.mongodb.database=aivice_db